version: "3.1"

services:

  server:
    image: nginx:latest
    container_name: app
    ports:
      - 8080:80
    volumes:
      - ./docker/hosts:/etc/hosts
      - ./docker/server.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
